---
title: "s16d"
author: "Emily Kubota"
date: "1/11/2022"
output: html_document
---

```{r}
# load in relevant functions & data 
library("tidyverse")
theme_set(theme_classic())
source("../../../code/utils/classification_plot.R")
df <- read.csv("../../data/s16d_classification.csv")
```

```{r}
# make the plot 
df %>% 
  classification_plot()

# save to figures folder
ggsave(filename = 
           paste0("s16d.png"),
        width = 6,
         height = 3)

ggsave(filename = 
           paste0("s16d.pdf"),
        width = 6,
         height = 3)
```

```{r}
df %>% 
  filter(classified_by %in% c("Cytoarchitecture","Category")) %>% 
  lmerTest::lmer(.,formula = Accuracy ~ classified_by * Group + (1|subject)) %>% 
  anova()
```
```{r}
# actually, let's do this as a GLM

df %>% 
  filter(classified_by %in% c("Cytoarchitecture","Category")) %>% 
   mutate(Accuracy = Accuracy/100) %>% 
  glm(.,formula = Accuracy ~ classified_by * Group,
      family = "binomial") %>% 
  summary()
```

```{r}

# test whether we can classify above chance for cyto

cyto_kid <- 
df %>% 
  filter(classified_by == 'Cytoarchitecture',
         Group == 'Children') %>% 
  select(Accuracy) 
  
t.test(cyto_kid,mu=50)

cyto_adult <- 
df %>% 
  filter(classified_by == 'Cytoarchitecture',
         Group == 'Adults') %>% 
  select(Accuracy) 
  
t.test(cyto_adult,mu=50)


```

```{r}

# test whether we can classify above chance for cat

cat_kid <- 
df %>% 
  filter(classified_by == 'Category',
         Group == 'Children') %>% 
  select(Accuracy) 
  
t.test(cat_kid,mu=50)

cat_adult <- 
df %>% 
  filter(classified_by == 'Category',
         Group == 'Adults') %>% 
  select(Accuracy) 
  
t.test(cat_adult,mu=50)


```

