---
title: "S13b"
author: "Emily Kubota"
date: "1/6/2022"
output: html_document
---

```{r}
# load in relevant functions & packages 
library("tidyverse")

# set the default ggplot theme 
theme_set(theme_classic())
```

```{r}
# read in the data 
df <- read.csv('../../data/fascicle_data_rh.csv')
```

```{r}
# change the order of the fascicles 
df <- 
  df %>% 
  mutate(tract = fct_relevel(tract, "IFOF","ILF","AF","pAF","VOF"),
         group = fct_relevel(group,"kid","adult"))
```

```{r}
# make the plot 
func_fascicle_plot_single_roi = function(df,hemi,agegroup,roiname){

# get the number of subjects 
foo <- 
df %>% 
    filter(group ==agegroup,
         hem == hemi,
         roi == roiname) 

n_subs <- length(unique(foo$subject))

  df %>% 
    filter(group ==agegroup,
         hem == hemi,
         roi == roiname) %>% 
    ggplot(aes(x = tract,
               y = percentage,
               fill = tract)) +
    stat_summary(fun = "mean",
                 geom = "bar") +
    stat_summary(fun.data = "mean_se",
                 geom = "linerange",
                 size = 1,
                 color = "black") +
    geom_point(alpha = 0.3,
               position = position_jitter(height = 0, width = 0.1),
               color ="gray",
               size = 2) +
    labs(x=element_blank(),y=("Percentage")) +
    theme(axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          legend.position = "none",
          aspect.ratio=1,
          text = element_text(size=20),
          element_line(size=1)) +
  
    scale_fill_manual(values = c("#007f7f", 
                                 "#cc4ccc", 
                                 "#cc0000",
                                 "#e57f00",
                                 "#99cc19")) +
    ylim(0,100) +
    ggtitle(roiname) +
    geom_text(x=1.25, y=90, label=paste0("n=",n_subs),size = 6)


# save to figures folder
ggsave(filename = 
           paste0("s13b_",roiname,"_",agegroup,".png"),
        width = 4,
         height = 3)

ggsave(filename = 
           paste0("s13b_",roiname,"_",agegroup,".pdf"),
        width = 4,
         height = 3)
}
```

```{r}
roinames = c("mFus-faces","pFus-faces","pOTS-words")

for (r in roinames){
      func_fascicle_plot_single_roi(df,"rh","adult",r)
  }
```