---
title: "fig1"
author: "Emily Kubota"
date: "1/6/2022"
output: html_document
---

```{r}
# load in relevant functions 
library("tidyverse")
# set the default ggplot theme 
theme_set(theme_classic())
```

```{r}
# read in the data 
df <- read.csv('../../../data/froi_croi_overlap.csv')

df.chance <- read.csv('../../../data/froi_croi_overlap_permutations.csv')
```

```{r}
df <-
df %>% 
  mutate(froi = recode(froi,
                       'mFus_Faces_cc3' = 'mFus-faces',
                       'mOTS_word_cc3' = 'mOTS-words',
                       'pFus_Faces_cc3' = 'pFus-faces',
                       'pOTS_word_cc3' = 'pOTS-words',
                       'OTS_Bodies_cc3' = 'OTS-bodies',
                        'PPA_Placeshouses_cc3' = 'CoS-places'),
         Group = recode(group,
                        'kid' = 'Children',
                        'adult' = 'Adults')) %>%
  mutate(Group = fct_relevel(Group, c("Children","Adults")))

df.chance <-
df.chance %>% 
  mutate(froi = recode(froi,
                       'mFus_Faces_cc3' = 'mFus-faces',
                       'mOTS_word_cc3' = 'mOTS-words',
                       'pFus_Faces_cc3' = 'pFus-faces',
                       'pOTS_word_cc3' = 'pOTS-words',
                       'OTS_Bodies_cc3' = 'OTS-bodies',
                        'PPA_Placeshouses_cc3' = 'CoS-places'),
         Group = recode(group,
                        'kid' = 'Children',
                        'adult' = 'Adults')) %>%
  mutate(Group = fct_relevel(Group, c("Children","Adults")))

```


```{r}
roi_overlap <- function(hem,roi_name) {
  # roi_name = 'mFus-faces'
  # calculate chance level
  
  chance <-
    df.chance %>%
    filter(
           froi == roi_name,
           hemi == hem) %>%
    summarize(
      mean_overlap = mean(overlap),
      se_overlap = sd(overlap)/sqrt(length(overlap)))
  
  line_add <-
    data.frame(
      x = c(0, 5),
      ymax = chance$mean_overlap + chance$se_overlap,
      ymin = chance$mean_overlap - chance$se_overlap
    )
  
  df %>%
    filter(hemi == hem,
           froi == roi_name) %>%
    ggplot(aes(
      x = croi,
      y = overlap,
      fill = interaction(Group, croi)
    )) +
    stat_summary(
      fun = "mean",
      geom = "bar",
      size = 1,
      position = position_dodge(.9)
    ) +
    stat_summary(
      fun.data = "mean_se",
      geom = "linerange",
      size = 1,
      position = position_dodge(.9)
    ) +
    scale_fill_manual(
      values = c(
        '#c0c0c0',
        '#808080',
        '#ccffff',
        '#00ffff',
        '#b3ffb3',
        '#00ff00',
        '#ffccff',
        '#ff00ff'
      )
    ) +
    #facet_wrap(~froi) +
    geom_hline(yintercept = chance$mean_overlap)+
  annotate('ribbon', 
           x = c(-Inf, Inf), 
           ymin = chance$mean_overlap - chance$se_overlap,
           ymax = chance$mean_overlap + chance$se_overlap, 
           alpha = 0.4, fill = 'gray') +
    theme(
      axis.title.x = element_blank(),
      legend.position = "none",
      aspect.ratio = 1,
      text = element_text(size = 12),
      element_line(size = 1)
    ) +
    coord_cartesian(ylim = c(0, 1)) +
    ylab('Proportion Overlap')
   ggsave(filename =
            paste0(hem,'_',roi_name,".pdf"),
         width = 2,
         height = 2)
}
```

```{r}
roi_overlap("lh","mFus-faces")
roi_overlap("rh","mFus-faces")

roi_overlap("lh","pFus-faces")
roi_overlap("rh","pFus-faces")

roi_overlap("lh","mOTS-words")

roi_overlap("lh","pOTS-words")
roi_overlap("rh","pOTS-words")
```
