---
title: "Fig 5A"
author: "Emily Kubota"
date: "1/6/2022"
output: html_document
---


```{r}
# load in relevant functions & packages 
source("../../utils/classification_plot.R")
library("tidyverse")

# set the default ggplot theme 
theme_set(theme_classic())
```

```{r}
# read in the data 
df <- read.csv('../../../data/fascicle_classification.csv')
```

```{r}
df %>% 
  filter(classified_by == "ROI") %>% 
  mutate(
           Group = fct_relevel(Group,c("Children","Adults"))) %>%
    ggplot(aes(x = actual_label,
               y = Accuracy,
               fill = Group)) +
    stat_summary(
      fun = "mean",
      geom = "bar",
   #   color = "gray",
      size = 4,
   position = position_dodge(.9)
    ) +
    stat_summary(
      fun.data = "mean_se",
      geom = "linerange",
    #  color = "black",
      size = 1,
     position = position_dodge(.9)
    ) +
    theme(
      axis.title.x = element_blank(),
      legend.position = "right",
      legend.text=element_text(size=8),
      legend.title=element_text(size=10),
      aspect.ratio = .5,
      text = element_text(size = 14),
      element_line(size = 1)
    ) +
    ylim(0, 100) +
    ylab("Classification Accuracy") +
    geom_segment(aes(
      x = .5,
      y = 25,
      xend = 4.5,
      yend = 25
    ),
    linetype = 'dashed',
    size = 1) +
  scale_fill_manual(values =c('#deebf7','#3182bd'))
```

```{r}
# calculate if classification is above chance for the kids 
mfus_kid <-
df %>% 
  filter(Group == "Children",
         actual_label == "mFus-faces")

mfus_kid <- mfus_kid$Accuracy 
t.test(mfus_kid,mu=25)

mots_kid <-
df %>% 
  filter(Group == "Children",
         actual_label == "mOTS-words")

mots_kid <- mots_kid$Accuracy 
t.test(mots_kid,mu=25)

pfus_kid <-
df %>% 
  filter(Group == "Children",
         actual_label == "pFus-faces")

pfus_kid <- pfus_kid$Accuracy 
t.test(pfus_kid,mu=25)

pots_kid <-
df %>% 
  filter(Group == "Children",
         actual_label == "pOTS-words")

pots_kid <- pots_kid$Accuracy 
t.test(pots_kid,mu=25)
```

```{r}

# calculate if classification is above chance for the adults 

mfus_adult <-
df %>% 
  filter(Group == "Adults",
         actual_label == "mFus-faces")

mfus_adult <- mfus_adult$Accuracy 
t.test(mfus_adult,mu=25)

mots_adult <-
df %>% 
  filter(Group == "Adults",
         actual_label == "mOTS-words")

mots_adult <- mots_adult$Accuracy 
t.test(mots_adult,mu=25)

pfus_adult <-
df %>% 
  filter(Group == "Adults",
         actual_label == "pFus-faces")

pfus_adult <- pfus_adult$Accuracy 
t.test(pfus_adult,mu=25)

pots_adult <-
df %>% 
  filter(Group == "Adults",
         actual_label == "pOTS-words")

pots_adult<- pots_adult$Accuracy 
t.test(pots_adult,mu=25)
```


```{r}
# save to figures folder
ggsave(filename = 
           paste0("fig5a.png"),
         width = 6,
        height = 2.5)

ggsave(filename = 
           paste0("fig5a.pdf"),
       width = 6,
      height = 2.5)
```