---
title: "Fig 3A"
author: "Emily Kubota"
date: "1/6/2022"
output: html_document
---

```{r}
# load in relevant functions & packages 
library("tidyverse")

# set the default ggplot theme 
theme_set(theme_classic())
```

```{r}
# read in the data 
df.distance <- read.csv('../../../data/distance.csv')
```

```{r}
# make the bar graph
df.distance %>%
  mutate(type =
           fct_relevel(type,
                       c('Functional ROI', 'Control ROI')),
         Group = fct_relevel(Group, c("Children", "Adults"))) %>%
  ggplot(aes(x = Cytoarchitecture,
             y = distance,
             fill = Group)) +
  stat_summary(
    fun = "mean",
    geom = "bar",
    size = 1,
    color = "black",
    position = position_dodge(.9)
  ) +
  stat_summary(
    fun.data = "mean_se",
    geom = "linerange",
    size = 1,
    position = position_dodge(.9)
  ) +
  theme(
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 12),
    aspect.ratio = 1,
    text = element_text(size = 20),
    element_line(size = 1)
  ) +
  coord_cartesian(ylim = c(0, 25)) +
  scale_fill_manual(values = c("white", "gray")) +
  ylab("Distance (mm)") +
  facet_grid( ~ type)

# save to figures folder
ggsave(filename = 
           paste0("fig3a.png"),
        width = 6,
         height = 4)
```

