---
title: "s14g"
author: "Emily Kubota"
date: "1/6/2022"
output: html_document
---

```{r}
# load in relevant functions & packages 
source("../../../code/utils/cor_mat_functions.R")
library("tidyverse")
library("patchwork")

# set the default ggplot theme 
theme_set(theme_classic())
```

```{r}
# read in the data 
df <- read.csv('../../../data/fascicle_data.csv')
df.age <- read.csv('../../../data/age_mapping.csv')
```

```{r}
# wrangle and combine dataframes 
df.age <- 
  df.age %>% 
  mutate(subject = sessid)

df <- merge(df,df.age)

```

```{r}
df <-
df %>% 
  filter(age >= 9) %>% 
  filter(age < 12 | age > 18)

df <-
df %>% 
  select(-c(sessid,anatid,fsid,age))

```

```{r}
# set the roi list 
roilist <- c('mOTS-words','mFus-faces','pOTS-words','pFus-faces')

#  make the correlation matrix 
a<- func_correlation_matrix_across_subs(df,"kid",roilist,'lh',sc,0,0) 
b<- func_correlation_matrix_across_subs(df,"adult",roilist,'lh',sc,0,0) 
a+b

# save to figures folder
ggsave(filename = "s14g.png",
        width = 8,
         height = 3)

# save to figures folder
ggsave(filename = "s14g.pdf",
        width = 8,
         height = 3)
```

```{r}
roipairs = list(c('mFus-faces','mOTS-words'),
                c('pFus-faces','pOTS-words'),
                c('mFus-faces','pFus-faces'),
                c('mOTS-words','pOTS-words'))
comparison_labs = c("same_cyto","same_cyto","same_domain","same_domain")

group = c("kid","adult")

for (i in 1:length(roipairs)) {
  for (g in group) {
    if ((i == 1) && (g == "kid")) {
      df.comparison <-
        tibble(
          func_corrrelations_across_subs_fisher(df, roipairs[[i]], 'lh',0, g),
          comparison = comparison_labs[i],
          group = g,
          roipair = paste0(roipairs[[i]][1],
                           "_vs_", roipairs[[i]][2])
        )
    }
    else{
      df.tmp <-
        tibble(
          func_corrrelations_across_subs_fisher(df, roipairs[[i]], 'lh', 0, g),
          comparison = comparison_labs[i],
          group = g,
          roipair = paste0(roipairs[[i]][1],
                           "_vs_", roipairs[[i]][2])
        )
      df.comparison <- rbind(df.comparison, df.tmp)
    }
  }
}

df.comparison %>% 
  group_by(roipair,group) %>% 
  summarize(mean_corr = mean(correlation),
            sd_corr = sd(correlation))
```

```{r}
df.comparison %>% 
  mutate(shared_factor = as.factor(comparison),
         group = as.factor(group)) %>% 
  lmerTest::lmer(.,formula = correlation ~ shared_factor * group + (1|subject)) %>% 
  anova()
```


